### ISSUE TITLE
java.lang.NoClassDefFoundError 崩溃

### ISSUE THREAD

**Issue by leonsu-l** [SkyDynamic/QuickBackupM-Fabric#10]
版本：1.20.1 Fabric

优化和辅助模组比较多，加载完世界之后崩溃
```
[12:10:04] [C2ME worker #2/INFO]: Preparing spawn area: 0%
[12:10:04] [DefaultDispatcher-worker-7/INFO]: Registry insert complete
[12:10:04] [minecraft_overworld - Light/INFO]: Preparing spawn area: 90%
[12:10:04] [Server thread/INFO]: Time elapsed: 655 ms
[12:10:04] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: org/bson/codecs/configuration/CodecProvider
```

（第一次提issue，可能有不规范的地方，请指出）

下面是崩溃日志：

```
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 2024-05-05 12:10:04

Description: Exception in server tick loop

java.lang.NoClassDefFoundError: org/bson/codecs/configuration/CodecProvider
	at dev.skydynamic.quickbackupmulti.QuickBackupMulti.setDataBase(QuickBackupMulti.java:108)
	at net.minecraft.server.MinecraftServer.handler$bmb000$quickbackupmulti$initQuickBackupMulti(MinecraftServer.java:4321)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:339)
	at net.minecraft.class_3176.method_3823(class_3176.java:169)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:646)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: org.bson.codecs.configuration.CodecProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 7 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 5.15.0-105-generic
	Java Version: 17.0.2, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 448527872 bytes (427 MiB) / 1291845632 bytes (1232 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 32
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i9-13900K
	Identifier: Intel64 Family 6 Model 183 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 24
	Number of logical CPUs: 32
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 24106.96
	Virtual memory used (MB): 9594.57
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 0.00
	JVM Flags: 3 total; -Xmx10G -XX:+ExplicitGCInvokesConcurrent -Xms1G
	Fabric Mods: 
		architectury: Architectury 9.2.14
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.10.94
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.10.94
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.10.94
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.10.94
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.10.94
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.10.94
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.10.94
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.10.94
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.10.94
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.10.94
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.10.94
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.10.94
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.10.94
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.10.94
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.10.94
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.10.94
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.10.94
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.94
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.10.94
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.94
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		chunky: Chunky 1.3.92
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		commandaliases: Command Aliases 1.0.1+mc1.20-build.68
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.15.2
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.15.2
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.15.2
			com_fasterxml_jackson_dataformat_jackson-dataformat-toml: jackson-dataformat-toml 2.15.2
			com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.15.2
			com_fathzer_javaluator: javaluator 3.0.3
			mysql_mysql-connector-java: mysql-connector-java 8.0.29
			org_apache_commons_commons-pool2: commons-pool2 2.11.1
			org_iq80_leveldb_leveldb: leveldb 0.12
			org_iq80_leveldb_leveldb-api: leveldb-api 0.12
			org_yaml_snakeyaml: snakeyaml 2.0
			redis_clients_jedis: jedis 4.2.3
		debugify: Debugify 1.20.1+2.0
		dynview: Dynamic View Mod 1.20.1-3.2
		essential_commands: Essential Commands 0.33.2-mc1.20
			ec-core: Essential Commands Core 1.3.0-mc1.20
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			placeholder-api: Placeholder API 2.1.1+1.20
			playerabilitylib: Pal 1.8.0
		fabric-api: Fabric API 0.92.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.10.10+kotlin.1.9.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
		fabricloader: Fabric Loader 0.15.10
			mixinextras: MixinExtras 0.3.5
		fancyclear: fancyclear 1.5.3
		farsight: Farsight Mod 1.20.1-3.9
			org_jctools_jctools-core: jctools-core 4.0.1
		forgeconfigapiport: Forge Config API Port 8.0.0
		invview: InvView 1.4.12-1.20+
			sgui: sgui 1.2.2+1.20
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.3.0.4
		lazydfu: LazyDFU 0.1.3
		ledger: Ledger 1.2.8
			server_translations_api: Server Translations API 2.0.0-beta.2+1.19.4-pre2
				packet_tweaker: Packet Tweaker 0.3.1+23w06a
		lithium: Lithium 0.11.2
		luckperms: LuckPerms 5.4.102
		memoryleakfix: Memory Leak Fix 1.1.2
		minecraft: Minecraft 1.20.1
		mixintrace: MixinTrace 1.1.1+1.17
		nochatreports: No Chat Reports 1.20.1-v2.2.2
		polylib: PolyLib 2000.0.3-build.133
			team_reborn_energy: Energy 2.2.0
		quickbackupmulti: QuickBackupMulti 2.0.1
			de_bwaldvogel_mongo-java-server: mongo-java-server 1.45.0
			de_bwaldvogel_mongo-java-server-h2-backend: mongo-java-server-h2-backend 1.45.0
			dev_morphia_morphia_morphia-core: morphia-core 2.3.9
			org_mongodb_mongodb-driver-sync: mongodb-driver-sync 4.11.1
			org_quartz-scheduler_quartz: quartz 2.3.2
		restart-server: Restart Server 1.2.0+mc1.19.x-1.20.x
		sleepatease: SleepAtEase 1.0.0
		smoothchunk: Smooth chunk save Mod 1.20.1-3.0
		spark: spark 1.10.53
		starlight: Starlight 1.1.2+fabric.dbc156f
		styledplayerlist: Styled Player List 3.1.1+1.20.1
			player-data-api: Player Data API 0.2.2+1.19.3
			predicate-api: Predicate API 0.1.2+1.20
		syncmatica: Syncmatica 1.20.1-0.3.10
		tick-stasis: Tick Stasis 1.0.0
		viaversion: ViaVersion 4.7.0
		vmp: Very Many Players 0.2.0+beta.7.97
		yet_another_config_lib_v3: YetAnotherConfigLib 3.1.1+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
		yosbr: YOSBR 0.1.2
	Server Running: true
	Player Count: 0 / 40; []
	Data Packs: vanilla, file/bukkit, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by SkyDynamic** [comment]
请使用action内版本，已经确定2.0 release存在问题

**Comment by SkyDynamic** [comment]
该issues将会关闭
