### ISSUE TITLE
1.16.5已安装fabric-api但仍报错

### ISSUE THREAD

**Issue by Qi-yuuu** [SkyDynamic/QuickBackupM-Fabric#13]
### Bug description / Bug描述

![报错](https://github.com/SkyDynamic/QuickBackupM-Fabric/assets/163987597/6a8e7f58-8006-4027-82d5-96a6b9c67860)

### Steps to reproduce / 复现步骤

安装malilib之后，提示需要安装fabric-api，但早已安装fabric-api

### Minecraft version / Minecraft版本

1.16.5

### Mod version / Mod版本

2.0.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
- [X] I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的

**Comment by SkyDynamic** [comment]
感谢issues, 咱一会测试一下怎么回事嗷

**Comment by michaelgsw** [comment]
实测 1.17.1也有同样的问题

**Comment by Qi-yuuu** [comment]
能问一下  哪里可以下载v2.0.3吗

**Comment by SkyDynamic** [comment]
> 能问一下  哪里可以下载v2.0.3吗
> 

action

**Comment by lmx0125** [comment]
在1.17.1服务端中会发生以下错误

A potential solution has been determined, this may resolve your problem:
         - Install fabric-api, any version.
More details:
         - Mod 'QuickBackupMulti' (quickbackupmulti) 2.0.2 requires any version of fabric-api, which is missing!
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:194) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.24.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:0.11.2]
可能是fabric-API版本低导致的
