### ISSUE TITLE
Fabric 1.20.1 Server 启动后崩溃

### ISSUE THREAD

**Issue by OcrSu** [SkyDynamic/QuickBackupM-Fabric#3]
Java17

```
[09:41:42] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "org.quartz.Scheduler.isStarted()" because "dev.skydynamic.quickbackupmulti.utils.config.Config.TEMP_CONFIG.scheduler" is null
	at net.minecraft.server.MinecraftServer.handler$coc000$quickbackupmulti$stopSchedule(MinecraftServer.java:10836) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3782(class_3176.java:537) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:703) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by OcrSu** [comment]
[2024-01-27-1.log](https://github.com/SkyDynamic/QuickBackupM-Fabric/files/14075651/2024-01-27-1.log)

**Comment by SkyDynamic** [comment]
535d3af8b290a5b550acaa1a200517c4cd020d61 已修
顺带一提，这个不是启动时崩溃的，是关闭服务器时候崩溃的

**Comment by OcrSu** [comment]
> [535d3af](https://github.com/SkyDynamic/QuickBackupM-Fabric/commit/535d3af8b290a5b550acaa1a200517c4cd020d61) 已修 顺带一提，这个不是启动时崩溃的，是关闭服务器时候崩溃的

嗯嗯，这是崩溃发生的几天后，我才想起来报issue，具体什么情况我也忘记了 :)

坐等推送新版，我再测试一下兼容性。

**Comment by SkyDynamic** [comment]
> > [535d3af](https://github.com/SkyDynamic/QuickBackupM-Fabric/commit/535d3af8b290a5b550acaa1a200517c4cd020d61) 已修 顺带一提，这个不是启动时崩溃的，是关闭服务器时候崩溃的
> 
> 嗯嗯，这是崩溃发生的几天后，我才想起来报issue，具体什么情况我也忘记了 :)
> 
> 坐等推送新版，我再测试一下兼容性。

你可以先下载action里面最新的snapshot build. 新版估计得等新功能上线了

**Comment by OcrSu** [comment]
> > > [535d3af](https://github.com/SkyDynamic/QuickBackupM-Fabric/commit/535d3af8b290a5b550acaa1a200517c4cd020d61) 已修 顺带一提，这个不是启动时崩溃的，是关闭服务器时候崩溃的
> > 
> > 
> > 嗯嗯，这是崩溃发生的几天后，我才想起来报issue，具体什么情况我也忘记了 :)
> > 坐等推送新版，我再测试一下兼容性。
> 
> 你可以先下载action里面最新的snapshot build. 新版估计得等新功能上线了

好的，正式推送的版本不急着用

**Comment by SkyDynamic** [comment]
请使用v1.0.4，本issue将关闭
