### ISSUE TITLE
当服务器发生大量卡顿时，无法执行回档操作

### ISSUE THREAD

**Issue by Roy-QQB-Huang** [SkyDynamic/QuickBackupM-Fabric#6]
测试时使用大量TNT矿车堆叠，使mspt高达150左右，在此情况下执行回档操作，重新连接后服务器并不能正常回档。
```[20:00:55] [Server thread/INFO]: QQB_Roy lost connection: Server restore backup
[20:00:55] [Server thread/INFO]: QQB_Roy left the game
[20:00:55] [Server thread/WARN]: handleDisconnection() called twice
[20:00:55] [Timer-10/ERROR]: Uncaught exception in thread "Timer-10"
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
        at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
        at dev.skydynamic.quickbackupmulti.backup.RestoreTask.run(RestoreTask.java:29) ~[QuickBackupMulti-mc1.20-v1.1.2.jar:?]
        at java.util.TimerThread.mainLoop(Timer.java:566) ~[?:?]
        at java.util.TimerThread.run(Timer.java:516) ~[?:?]
[20:00:55] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 18495ms or 369 ticks behind```

**Comment by SkyDynamic** [comment]
怎么自动关了...
